### ISSUE TITLE
This package breaks including regular css

### ISSUE THREAD

**Issue by mennovanhout** [leinelissen/laravel-mix-react-css-modules#7]
I'm trying to use bootstrap together with react including de css style like this:
import 'bootstrap/dist/css/bootstrap.css';

hoewever as soon as you change webpack to use .reactCSSModules the system breaks.
Col,Container,Rows won't get their bootstrap css anymore......

**Comment by leinelissen** [comment]
Hi Menno!

This plugin is based on a concept called [CSS Modules](https://github.com/css-modules/css-modules). What this means, is that for every CSS import, all classnames will be assigned a randomised name, while outputting a JavaScript object with a map for the original classnames to the new, random classnames. What this means is that you've successfully imported the CSS file, but the classnames are now different. There are a number of ways to go from here:

**1. You don't really need CSS Modules**
If you just want to import CSS and have it nicely concatenated, that's great! You don't need this plugin. Just setup Laravel Mix with React, and you're good to go. 

**2. Easy fix: Include bootstrap CDN**
Rather than bundling bootstrap yourself, you could opt for just including the CSS and JavaScript in your HTML file directly in your Blade template (see [this](https://getbootstrap.com/docs/4.3/getting-started/introduction/)). The performance penalty will most likely be negligible.

**3. More complicated fix: SCSS magic**
As can be seen from the [CSS modules docs](https://github.com/css-modules/css-modules), it is possible to define blocks of global CSS that won't get their classnames changed. You could define such a block, in which you import the bootstrap CSS file, as such:
```scss
:global {
  @import "../../../blahblah/bootstrap.css"
}
```

Alternatively, you could do a deep dive and exclude the bootstrap files, in which case you have no need for this plugin either. Let me know if this works out for you.

Cheers!
Lei
